name: sly
description: "Friendly image editor"
publish_to: "none"

version: 0.3.3

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  window_manager: ^0.4.2
  handy_window: ^0.4.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  file_selector: ^1.0.3
  image_picker: ^1.1.2
  gal: ^2.3.0
  image: ^4.2.0
  crop_image: ^1.0.13
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  msix: ^3.16.8

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/1.5x/
    - assets/icons/2.0x/
    - assets/icons/3.0x/
    - assets/icons/4.0x/

  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Thin.otf
          weight: 100
        - asset: assets/fonts/Geist-UltraLight.otf
          weight: 200
        - asset: assets/fonts/Geist-Light.otf
          weight: 300
        - asset: assets/fonts/Geist-Regular.otf
          weight: 400
        - asset: assets/fonts/Geist-Medium.otf
          weight: 500
        - asset: assets/fonts/Geist-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Geist-Bold.otf
          weight: 700
        - asset: assets/fonts/Geist-Black.otf
          weight: 800
        - asset: assets/fonts/Geist-UltraBlack.otf
          weight: 900

msix_config:
  display_name: Sly
  publisher_display_name: kramo
  identity_name: page.kramo.Sly
  logo_path: .\windows\runner\resources\app_icon.ico
  install_certificate: false
