# https://github.com/localsend/localsend/blob/135939850291f6d15c984307cc9186f2ac5c9b36/.github/workflows/release.yml
#Â https://github.com/kra-mo/cartridges/blob/2801e777f785428614dab48cb6aa79068dc8ee67/.github/workflows/ci.yml

name: CI
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: release-${{ github.sha }}

jobs:
  android:
    name: Android
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build for Android
        run: flutter build apk --split-per-abi --release

      - name: Zip compiled files
        run: |
          cd build/app/outputs/flutter-apk/
          zip -yr Sly.zip *.apk

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: Android APK
          path: build/app/outputs/flutter-apk/Sly.zip

  linux:
    name: Linux
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake libgtk-3-dev ninja-build

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build for Linux
        run: flutter build linux --release

      - name: Create tar.gz archive
        run: |
          cd build/linux/x64/release/bundle
          tar -czvf ../../../../../Sly.tar.gz *

      - name: Upload tar.gz archive
        uses: actions/upload-artifact@v4
        with:
          name: Linux Binary
          path: ./*.tar.gz

  macos:
    name: macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build for macOS
        run: flutter build macos --release

      - name: Zip compiled files
        run: |
          cd build/macos/Build/Products/Release
          zip -yr Sly.zip Sly.app

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: macOS Application
          path: build/macos/Build/Products/Release/Sly.zip

  windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: Fix long file paths
        run: git config --system core.longpaths true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Build for Windows
        run: flutter build windows --release

      - name: Add DLL files
        run: |
          tree /F
          Copy-Item C:\\Windows\\System32\\msvcp140.dll build/windows/x64/runner/Release/
          Copy-Item C:\\Windows\\System32\\vcruntime140.dll build/windows/x64/runner/Release/
          Copy-Item C:\\Windows\\System32\\vcruntime140_1.dll build/windows/x64/runner/Release/

      - name: Zip compiled files
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath Sly.zip

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: Windows Executable
          path: Sly.zip
